[home_servers]
home-server ansible_host="{{ lookup('env', 'SERVER_IP') }}" ansible_user="{{ lookup('env', 'SERVER_USER') }}" ansible_ssh_private_key_file="{{ lookup('env', 'SSH_KEY_PATH') }}"

[home_servers:vars]
target_user="{{ lookup('env', 'SERVER_USER') }}"
ssh_port=22
tailscale_ssh=true
docker_base_dir=/opt/docker
ansible_become_exe=/usr/bin/sudo.ws

